apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: rileyfinal
  name: characterbuilder-prometheus-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi