scrape_configs:
  - job_name: blackbox
    metrics_path: /probe
    scrape_interval: 5s
    params:
      module: [http_2xx]
    static_configs:
    - targets:
      - http://characterbuilderapi-service:80
      - http://characterbuilderweb-service:80
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox-service:9115  
  - job_name: 'API Web Metrics'
    scrape_interval: 10s
    static_configs:
    - targets:
      - characterbuilderapi-service:80
      - characterbuilderweb-service:80
