
version: '3.8'

volumes:
  dbVolume:

services:

  charactertesting:
    container_name: charactertesting
    command: tail -f /dev/null
    build: 
        context: ..
        dockerfile: ./CharacterTests/Dockerfile
    stdin_open: true
    tty: true


  
  postgres:
    container_name: test-my_postgres_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=myusername
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      -  dbVolume:/var/lib/postgresql/data
    ports:
      - "5437:5432"




  

  