{
 "title": "Character stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Characters right now",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Charactercount_Characters", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Character Edits",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "CharactersUpdated_characterupdate_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deleted Characters",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "CharactersDeleted_characterdelete_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}