{
 "title": "Logs and Errors",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Uptime Website Past Hour",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=\"http://characterbuilder-service:80\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Api Uptime Over Past Hour",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=\"http://characterbuilderapi-service:80\"}[1h])"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} |= `an error` | json"
    }
   ]
  },
  {
   "title": "Home Page Traffic",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(homepage_homepageviews_total{instance=\"characterbuilder-service:80\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(characterpage_characterpageviews_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Player Page Traffic",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(playerpage_playerpageviews_total{job=\"API Web Metrics\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Player Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} | json |= `player`"
    }
   ]
  },
  {
   "title": "Character Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} |= `character` | json"
    }
   ]
  }
 ]
}