{
 "title": "Overall",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Players Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Playercount_Players", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Character Total",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Charactercount_Characters", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Api Visits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "apiviews_views_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Player Creation History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "Playercount_Players", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Character Creation History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "Charactercount_Characters", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Updated Players",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "PlayersUpdated_playerupdate_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "kestrel_active_connections", "legendFormat": "__auto" }
   ]
  }
 ]
}