{
 "title": "Players General",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Player Updated",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "PlayersUpdated_playerupdate_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Players Deleted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "PlayersDeleted_playerdelete_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Players",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Playercount_Players", "legendFormat": "__auto" }
   ]
  }
 ]
}