name: backup database
on:
    - workflow_dispatch
jobs:
    backup:
        runs-on: self-hosted
        steps:
            - name: backup
              run: |
                CONTAINER_NAME=$(kubectl -n rileyfinal get pods --no-headers -o custom-columns=":metadata.name" | grep "characterbuilder-db-deployment")
                kubectl -n rileyfinal exec -t $CONTAINER_NAME -- \
                    pg_dumpall -c -U riley-user \
                    > /home/riley/backup.sql