name: pull request environment
on:
    pull_request:
        types: [opened, reopened]
jobs:
    deploy-to-kubernetes:
        runs-on: self-hosted
        steps:
            - name: check out code
              uses: actions/checkout@v4

            - name: deploy kubernetes environment
              run: |
                export PULL_REQUEST_ID=${{ github.event.pull_request.number }}
                export NAMESPACE="rileyfinal-pr-$PULL_REQUEST_ID"
                kubectl create namespace $NAMESPACE || true

                kubectl -n $NAMESPACE delete configmap characterbuilder-postgres-init || true
                kubectl -n $NAMESPACE create configmap characterbuilder-postgres-init --from-file=init.sql

                export RUN_SALT="pr-${$GITHUB_RUN_ID}-"
                docker build -t 144.17.92.12:5000/rileyfinal/characterbuilder:$GITHUB_RUN_ID -f CharacterBuilderWeb/Dockerfile .